Export vm-bhyve in fucntions, get vmdir, and fix get libs * Export vm-bhyve command so that it can be used in functions-vm. * We must get vmdir for when we run vm-bhyve from other directories. * Also fix get libs so that it works when we run vm-bhyve from other directories.

diff --git a/utils/vm-bhyve/vm-bhyve b/utils/vm-bhyve/vm-bhyve
--- a/utils/vm-bhyve/vm-bhyve
+++ b/utils/vm-bhyve/vm-bhyve
@@ -26,8 +26,6 @@
 #
 # Modified for ixautomation project by Joe Maloney ( jmaloney@ixsystems.com )
 
-export vm_dir="../../vms"
-
 VERSION=1.1-p8
 VERSION_INT=101073
 VERSION_BSD=$(uname -K)
@@ -36,9 +34,21 @@ PATH=${PATH}:/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin
 . /etc/rc.subr
 load_rc_config "vm"
 
+# get vmdir
+if [ -d "../../vms" ]; then
+    export vm_dir="../../vms"
+elif [ -d "../vms" ]; then
+    export vm_dir="../vms"
+else
+    echo "unable to locate vm-dir"
+    exit 1
+fi
+
 # get libs
 if [ -e "./lib/vm-core" ]; then
     LIB="./lib"
+elif [ -e "../utils/vm-bhyve/lib" ]; then
+    LIB="../utils/vm-bhyve/lib"
 else
     echo "unable to locate vm-bhyve libriaries"
     exit 1
